---
- hosts: localhost
  connection: local
  tasks:
    - community.docker.docker_container:
        name: myhello
        image: eomjinyoung/myhello:latest
        state: started
        pull: always
        recreate: true
        ports:
          - "80:8080"
